// crates/templates/files/{{cookiecutter.project_slug}}/{% if cookiecutter.frontend != 'nuxt' or cookiecutter.is_skeleton %}__SKIP__{% endif %}frontend/app/pages/account/mfa-activate.vue
<script setup lang="ts">
definePageMeta({ middleware: "auth" });
useSeoMeta({ title: "Set up two-factor auth" });

const uri = ref<string | null>(null);
const secret = ref<string | null>(null);
const code = ref("");
const error = ref<string | null>(null);
const done = ref(false);
const busy = ref(false);
const router = useRouter();
const auth = useAuthStore();

const qrSrc = computed(() =>
  uri.value ? `https://quickchart.io/qr?text=${encodeURIComponent(uri.value)}&size=220` : null,
);

onMounted(async () => {
  const r = await auth.mfaActivateBegin();
  if (r.kind === "ok") {
    uri.value = r.uri;
    secret.value = r.secret;
  } else {
    error.value = "Couldn't start TOTP enrollment.";
  }
});

async function onConfirm(e: Event) {
  e.preventDefault();
  error.value = null;
  if (code.value.length < 6) {
    error.value = "Enter the 6-digit code from your authenticator.";
    return;
  }
  busy.value = true;
  const r = await auth.mfaActivateConfirm(code.value);
  busy.value = false;
  if (r.kind === "ok") {
    done.value = true;
    setTimeout(() => router.push("/account/recovery-codes"), 1200);
  } else {
    error.value = "That code didn't match. Check the time on your device and try again.";
  }
}

function sanitize(v: string) {
  code.value = v.replace(/[^0-9]/g, "").slice(0, 6);
}
</script>

<template>
  <section class="mx-auto max-w-md space-y-5 py-6">
    <h1 class="text-3xl font-semibold">Set up two-factor auth</h1>
    <div
      v-if="done"
      class="rounded-md border border-green-300 bg-green-50 px-3 py-3 text-sm text-green-800 dark:border-green-900 dark:bg-green-950 dark:text-green-100"
    >
      ✔ MFA enabled. Redirecting to your recovery codes…
    </div>
    <template v-else>
      <p class="text-sm text-slate-600 dark:text-slate-400">
        Scan this QR code with an authenticator app (1Password, Authy, Google Authenticator) — or enter
        the secret manually.
      </p>
      <div v-if="uri" class="rounded-md border border-slate-200 bg-slate-50 p-4 dark:border-slate-800 dark:bg-slate-900">
        <img :src="qrSrc!" alt="Two-factor QR code" width="220" height="220" class="block" />
        <p class="mt-3 text-xs text-slate-500 dark:text-slate-400">
          Secret: <code class="rounded bg-slate-100 px-1 py-0.5 dark:bg-slate-800">{{ '{{' }} secret {{ '}}' }}</code>
        </p>
      </div>
      <p v-else class="text-sm text-slate-500">Generating…</p>
      <div
        v-if="error"
        role="alert"
        class="rounded-md border border-red-300 bg-red-50 px-3 py-2 text-sm text-red-800 dark:border-red-900 dark:bg-red-950 dark:text-red-200"
      >
        {{ '{{' }} error {{ '}}' }}
      </div>
      <form aria-label="Confirm MFA" class="space-y-3" @submit="onConfirm">
        <label class="block text-sm font-medium">Enter the 6-digit code to confirm</label>
        <input
          :value="code"
          inputmode="numeric"
          pattern="[0-9]*"
          autocomplete="one-time-code"
          maxlength="6"
          placeholder="123 456"
          class="block w-full rounded-md border border-slate-300 px-3 py-2 text-center tracking-widest dark:border-slate-700 dark:bg-slate-900"
          @input="(e) => sanitize((e.target as HTMLInputElement).value)"
        />
        <button
          type="submit"
          :disabled="busy"
          class="w-full rounded-md bg-slate-900 px-4 py-2 text-sm font-medium text-white hover:bg-slate-700 disabled:opacity-50 dark:bg-slate-100 dark:text-slate-900"
        >
          {{ '{{' }} busy ? "Activating…" : "Activate MFA" {{ '}}' }}
        </button>
      </form>
    </template>
  </section>
</template>

// crates/templates/files/{{cookiecutter.project_slug}}/{% if cookiecutter.frontend != 'next' or cookiecutter.is_skeleton %}__SKIP__{% endif %}frontend/app/account/mfa-activate/page.tsx
"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Box, Button, Callout, Code, Flex, Heading, Text, TextField } from "@radix-ui/themes";
import { ExclamationTriangleIcon, CheckCircledIcon } from "@radix-ui/react-icons";

import { authClient } from "~/lib/auth/client";
import { useAuth } from "~/lib/auth/store";

export default function MfaActivatePage() {
  const { user, status } = useAuth();
  const router = useRouter();

  useEffect(() => {
    if (status === "loaded" && !user) {
      router.replace("/account/login?next=/account/mfa-activate");
    }
  }, [status, user, router]);

  const [uri, setUri] = useState<string | null>(null);
  const [secret, setSecret] = useState<string | null>(null);
  const [code, setCode] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [done, setDone] = useState(false);
  const [busy, setBusy] = useState(false);

  useEffect(() => {
    if (!user) return;
    void (async () => {
      const r = await authClient.mfaActivateBegin();
      if (r.kind === "ok") {
        setUri(r.uri);
        setSecret(r.secret);
      } else {
        setError("Couldn't start TOTP enrollment.");
      }
    })();
  }, [user]);

  async function onConfirm(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();
    setError(null);
    if (code.length < 6) {
      setError("Enter the 6-digit code from your authenticator.");
      return;
    }
    setBusy(true);
    const r = await authClient.mfaActivateConfirm(code);
    setBusy(false);
    if (r.kind === "ok") {
      setDone(true);
      setTimeout(() => router.push("/account/recovery-codes"), 1200);
    } else {
      setError("That code didn't match. Check the time on your device and try again.");
    }
  }

  if (!user) return null;

  return (
    <Flex direction="column" gap="4">
      <Heading size="6">Set up two-factor auth</Heading>
      {done ? (
        <Callout.Root color="green">
          <Callout.Icon>
            <CheckCircledIcon />
          </Callout.Icon>
          <Callout.Text>MFA enabled. Redirecting to your recovery codes…</Callout.Text>
        </Callout.Root>
      ) : (
        <>
          <Text size="2" color="gray">
            Scan this QR code with an authenticator app (1Password, Authy, Google Authenticator) —
            or enter the secret manually.
          </Text>
          {uri ? (
            <Box
              style={{
                background: "var(--gray-3)",
                padding: "1.5rem",
                borderRadius: "var(--radius-3)",
              }}
            >
              <img
                src={`https://quickchart.io/qr?text=${encodeURIComponent(uri)}&size=220`}
                alt="Two-factor QR code"
                width={220}
                height={220}
                style={{ display: "block" }}
              />
              <Text as="div" size="1" color="gray" mt="3">
                Secret: <Code>{secret}</Code>
              </Text>
            </Box>
          ) : (
            <Text size="2" color="gray">
              Generating…
            </Text>
          )}
          {error ? (
            <Callout.Root color="red" role="alert">
              <Callout.Icon>
                <ExclamationTriangleIcon />
              </Callout.Icon>
              <Callout.Text>{error}</Callout.Text>
            </Callout.Root>
          ) : null}
          <form onSubmit={onConfirm} aria-label="Confirm MFA">
            <Flex direction="column" gap="3">
              <Text as="div" size="2" weight="medium">
                Enter the 6-digit code to confirm
              </Text>
              <TextField.Root
                inputMode="numeric"
                pattern="[0-9]*"
                autoComplete="one-time-code"
                maxLength={6}
                placeholder="123 456"
                value={code}
                onChange={(e) => setCode(e.currentTarget.value.replace(/[^0-9]/g, ""))}
              />
              <Button type="submit" size="3" loading={busy} disabled={busy}>
                Activate MFA
              </Button>
            </Flex>
          </form>
        </>
      )}
    </Flex>
  );
}
