// crates/templates/files/{{cookiecutter.project_slug}}/{% if cookiecutter.frontend != 'react' or cookiecutter.is_skeleton %}__SKIP__{% endif %}frontend/src/routes/account/verify-email.tsx
import { Box, Callout, Flex, Heading, Text } from "@radix-ui/themes";
import { EnvelopeClosedIcon } from "@radix-ui/react-icons";

export function VerifyEmailPage() {
  return (
    <Flex direction="column" gap="4">
      <Heading size="6">Check your email</Heading>
      <Callout.Root>
        <Callout.Icon>
          <EnvelopeClosedIcon />
        </Callout.Icon>
        <Callout.Text>
          We&apos;ve sent you a confirmation link. Click it to verify your address — then come back
          and sign in.
        </Callout.Text>
      </Callout.Root>
      <Box>
        <Text size="2" color="gray">
          Tip: in local dev the email lands in <a href="http://localhost:8025" target="_blank" rel="noreferrer">Mailpit</a>.
        </Text>
      </Box>
    </Flex>
  );
}

// crates/templates/files/{{bakery.project_slug}}/{% if bakery.frontend != 'nuxt' or bakery.is_skeleton %}__SKIP__{% endif %}frontend/app/pages/account/verify-email.vue
<script setup lang="ts">
definePageMeta({ layout: "account" });
useSeoMeta({ title: "Verify your email" });
</script>

<template>
  <div class="space-y-4">
    <h1 class="text-2xl font-semibold">Check your email</h1>
    <div class="rounded-md border border-blue-200 bg-blue-50 p-4 text-sm text-blue-900 dark:border-blue-900 dark:bg-blue-950 dark:text-blue-100">
      We've sent you a confirmation link. Click it to verify your address — then come back and sign in.
    </div>
    <p class="text-sm text-slate-500 dark:text-slate-400">
      Tip: in local dev the email lands in
      <a href="http://localhost:8025" target="_blank" rel="noreferrer" class="underline">Mailpit</a>.
    </p>
  </div>
</template>
