// crates/templates/files/{{bakery.project_slug}}/{% if bakery.frontend != 'next' or bakery.is_skeleton %}__SKIP__{% endif %}frontend/app/account/login/page.tsx
"use client";

import { useState } from "react";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { Button, Callout, Flex, Heading, Text, TextField } from "@radix-ui/themes";
import { ExclamationTriangleIcon } from "@radix-ui/react-icons";
import { z } from "zod";

import { authClient } from "~/lib/auth/client";
import { useAuthStore } from "~/lib/auth/store";

const schema = z.object({
  email: z.email("Enter a valid email"),
  password: z.string().min(1, "Password is required"),
});

export default function LoginPage() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const router = useRouter();
  const params = useSearchParams();
  const setUser = useAuthStore((s) => s.setUser);

  async function onSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();
    setError(null);
    const parsed = schema.safeParse({ email, password });
    if (!parsed.success) {
      setError(parsed.error.issues[0]?.message ?? "Invalid input");
      return;
    }
    setBusy(true);
    const result = await authClient.login(parsed.data.email, parsed.data.password);
    setBusy(false);
    switch (result.kind) {
      case "ok":
        setUser(result.user);
        router.push(params.get("next") ?? "/account/profile");
        return;
      case "mfa_required":
        router.push("/account/mfa-challenge");
        return;
      case "email_verification_required":
        router.push("/account/verify-email");
        return;
      case "invalid_credentials":
        setError("Incorrect email or password.");
        return;
      case "rate_limited":
        setError("Too many attempts. Try again in about 5 minutes.");
        return;
      default:
        setError("Something went wrong. Please try again.");
    }
  }

  return (
    <Flex direction="column" gap="4">
      <Heading size="6">Sign in</Heading>
      <Text size="2" color="gray">
        Use your email and password.
      </Text>
      {error ? (
        <Callout.Root color="red" role="alert">
          <Callout.Icon>
            <ExclamationTriangleIcon />
          </Callout.Icon>
          <Callout.Text>{error}</Callout.Text>
        </Callout.Root>
      ) : null}
      <form onSubmit={onSubmit} aria-label="Sign in">
        <Flex direction="column" gap="3">
          <label>
            <Text as="div" size="2" weight="medium" mb="1">
              Email
            </Text>
            <TextField.Root
              type="email"
              autoComplete="email"
              required
              value={email}
              onChange={(e) => setEmail(e.currentTarget.value)}
            />
          </label>
          <label>
            <Text as="div" size="2" weight="medium" mb="1">
              Password
            </Text>
            <TextField.Root
              type="password"
              autoComplete="current-password"
              required
              value={password}
              onChange={(e) => setPassword(e.currentTarget.value)}
            />
          </label>
          <Button type="submit" size="3" loading={busy} disabled={busy}>
            Sign in
          </Button>
        </Flex>
      </form>
      <Text size="2" color="gray">
        New here? <Link href="/account/signup">Create an account</Link>
      </Text>
    </Flex>
  );
}

// crates/templates/files/{{cookiecutter.project_slug}}/{% if cookiecutter.frontend != 'nuxt' or cookiecutter.is_skeleton %}__SKIP__{% endif %}frontend/app/pages/account/login.vue
<script setup lang="ts">
import { z } from "zod";

definePageMeta({ layout: "account", middleware: "guest" });

const schema = z.object({
  email: z.email("Enter a valid email"),
  password: z.string().min(1, "Password is required"),
});

const email = ref("");
const password = ref("");
const error = ref<string | null>(null);
const busy = ref(false);

const route = useRoute();
const router = useRouter();
const auth = useAuthStore();

async function onSubmit(e: Event) {
  e.preventDefault();
  error.value = null;
  const parsed = schema.safeParse({ email: email.value, password: password.value });
  if (!parsed.success) {
    error.value = parsed.error.issues[0]?.message ?? "Invalid input";
    return;
  }
  busy.value = true;
  const result = await auth.login(parsed.data.email, parsed.data.password);
  busy.value = false;
  switch (result.kind) {
    case "ok":
      await router.push((route.query.next as string) || "/account/profile");
      return;
    case "mfa_required":
      await router.push("/account/mfa-challenge");
      return;
    case "email_verification_required":
      await router.push("/account/verify-email");
      return;
    case "invalid_credentials":
      error.value = "Incorrect email or password.";
      return;
    case "rate_limited":
      error.value = "Too many attempts. Try again in about 5 minutes.";
      return;
    default:
      error.value = "Something went wrong. Please try again.";
  }
}
</script>

<template>
  <div class="space-y-4">
    <h1 class="text-2xl font-semibold">Sign in</h1>
    <p class="text-sm text-slate-600 dark:text-slate-400">Use your email and password.</p>
    <div
      v-if="error"
      role="alert"
      class="rounded-md border border-red-300 bg-red-50 px-3 py-2 text-sm text-red-800 dark:border-red-900 dark:bg-red-950 dark:text-red-200"
    >
      {{ error }}
    </div>
    <form aria-label="Sign in" class="space-y-3" @submit="onSubmit">
      <label class="block text-sm">
        <span class="font-medium">Email</span>
        <input
          v-model="email"
          type="email"
          autocomplete="email"
          required
          class="mt-1 block w-full rounded-md border border-slate-300 px-3 py-2 dark:border-slate-700 dark:bg-slate-900"
        />
      </label>
      <label class="block text-sm">
        <span class="font-medium">Password</span>
        <input
          v-model="password"
          type="password"
          autocomplete="current-password"
          required
          class="mt-1 block w-full rounded-md border border-slate-300 px-3 py-2 dark:border-slate-700 dark:bg-slate-900"
        />
      </label>
      <button
        type="submit"
        :disabled="busy"
        class="w-full rounded-md bg-slate-900 px-4 py-2 text-sm font-medium text-white hover:bg-slate-700 disabled:opacity-50 dark:bg-slate-100 dark:text-slate-900"
      >
        {{ busy ? "Signing in…" : "Sign in" }}
      </button>
    </form>
    <p class="text-sm text-slate-600 dark:text-slate-400">
      New here? <NuxtLink to="/account/signup" class="underline">Create an account</NuxtLink>
    </p>
  </div>
</template>
