// crates/templates/files/{{cookiecutter.project_slug}}/{% if cookiecutter.frontend != 'react' %}__SKIP__{% endif %}frontend/src/routes/account/mfa-challenge.tsx
import { useState } from "react";
import { useNavigate } from "react-router";
import { Button, Callout, Flex, Heading, Text, TextField } from "@radix-ui/themes";
import { ExclamationTriangleIcon } from "@radix-ui/react-icons";

import { authClient } from "~/auth/client";
import { useAuthStore } from "~/auth/store";

export function MfaChallengePage() {
  const [code, setCode] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const navigate = useNavigate();
  const setUser = useAuthStore((s) => s.setUser);

  async function onSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();
    setError(null);
    if (code.length < 6) {
      setError("Enter the 6-digit code from your authenticator app.");
      return;
    }
    setBusy(true);
    const result = await authClient.mfaAuthenticate(code);
    setBusy(false);
    switch (result.kind) {
      case "ok":
        setUser(result.user);
        navigate("/account/profile");
        return;
      case "invalid_credentials":
        setError("That code didn't match. Try again.");
        return;
      case "rate_limited":
        setError("Too many attempts. Wait a few minutes.");
        return;
      default:
        setError("Couldn't verify. Try again.");
    }
  }

  return (
    <Flex direction="column" gap="4">
      <Heading size="6">Two-factor code</Heading>
      <Text size="2" color="gray">
        Enter the 6-digit code from your authenticator app.
      </Text>
      {error ? (
        <Callout.Root color="red" role="alert">
          <Callout.Icon>
            <ExclamationTriangleIcon />
          </Callout.Icon>
          <Callout.Text>{error}</Callout.Text>
        </Callout.Root>
      ) : null}
      <form onSubmit={onSubmit} aria-label="MFA code">
        <Flex direction="column" gap="3">
          <TextField.Root
            inputMode="numeric"
            pattern="[0-9]*"
            autoComplete="one-time-code"
            maxLength={6}
            placeholder="123 456"
            value={code}
            onChange={(e) => setCode(e.currentTarget.value.replace(/[^0-9]/g, ""))}
          />
          <Button type="submit" size="3" loading={busy} disabled={busy}>
            Verify
          </Button>
        </Flex>
      </form>
    </Flex>
  );
}

// crates/templates/files/{{cookiecutter.project_slug}}/{% if cookiecutter.frontend != 'nuxt' or cookiecutter.is_skeleton %}__SKIP__{% endif %}frontend/app/pages/account/mfa-challenge.vue
<script setup lang="ts">
definePageMeta({ layout: "account" });
useSeoMeta({ title: "Two-factor code" });

const code = ref("");
const error = ref<string | null>(null);
const busy = ref(false);
const router = useRouter();
const auth = useAuthStore();

async function onSubmit(e: Event) {
  e.preventDefault();
  error.value = null;
  if (code.value.length < 6) {
    error.value = "Enter the 6-digit code from your authenticator app.";
    return;
  }
  busy.value = true;
  const result = await auth.mfaAuthenticate(code.value);
  busy.value = false;
  switch (result.kind) {
    case "ok":
      await router.push("/account/profile");
      return;
    case "invalid_credentials":
      error.value = "That code didn't match. Try again.";
      return;
    case "rate_limited":
      error.value = "Too many attempts. Wait a few minutes.";
      return;
    default:
      error.value = "Couldn't verify. Try again.";
  }
}

function sanitize(v: string) {
  code.value = v.replace(/[^0-9]/g, "").slice(0, 6);
}
</script>

<template>
  <div class="space-y-4">
    <h1 class="text-2xl font-semibold">Two-factor code</h1>
    <p class="text-sm text-slate-600 dark:text-slate-400">Enter the 6-digit code from your authenticator app.</p>
    <div
      v-if="error"
      role="alert"
      class="rounded-md border border-red-300 bg-red-50 px-3 py-2 text-sm text-red-800 dark:border-red-900 dark:bg-red-950 dark:text-red-200"
    >
      {{ '{{' }} error {{ '}}' }}
    </div>
    <form aria-label="MFA code" class="space-y-3" @submit="onSubmit">
      <input
        :value="code"
        inputmode="numeric"
        pattern="[0-9]*"
        autocomplete="one-time-code"
        maxlength="6"
        placeholder="123456"
        class="block w-full rounded-md border border-slate-300 px-3 py-2 text-center tracking-widest dark:border-slate-700 dark:bg-slate-900"
        @input="(e) => sanitize((e.target as HTMLInputElement).value)"
      />
      <button
        type="submit"
        :disabled="busy"
        class="w-full rounded-md bg-slate-900 px-4 py-2 text-sm font-medium text-white hover:bg-slate-700 disabled:opacity-50 dark:bg-slate-100 dark:text-slate-900"
      >
        {{ '{{' }} busy ? "Verifying…" : "Verify" {{ '}}' }}
      </button>
    </form>
  </div>
</template>
