// crates/templates/files/{{cookiecutter.project_slug}}/{% if cookiecutter.frontend != 'next' or cookiecutter.is_skeleton %}__SKIP__{% endif %}frontend/app/account/profile/page.tsx
import { redirect } from "next/navigation";
import Link from "next/link";
import { Badge, Box, Button, Container, Flex, Heading, Text } from "@radix-ui/themes";
import { LockClosedIcon } from "@radix-ui/react-icons";

import { currentUser } from "~/lib/auth/server";

export const metadata = { title: "Profile" };

/**
 * Server Component auth gate.
 *
 * The redirect happens on the SERVER — there's no flash of empty content, no
 * client-side waterfall, and the unauthenticated user never sees a request go
 * out for protected data. The Django backend remains the final authority for
 * authorization on every fetch the page initiates.
 */
export default async function ProfilePage() {
  const user = await currentUser();
  if (!user) {
    redirect("/account/login?next=/account/profile");
  }

  const mfaOn = user.has_usable_mfa === true;

  return (
    <Container size="3">
      <Flex direction="column" gap="5" py="6">
        <Box>
          <Heading size="6">Your profile</Heading>
          <Text size="2" color="gray">
            Signed in as {user.email}
          </Text>
        </Box>
        <Flex direction="column" gap="3">
          <Row label="Email" value={user.email} />
          <Row label="Full name" value={user.full_name || "—"} />
          <Row
            label="Multi-factor auth"
            value={
              <Flex align="center" gap="2">
                <Badge color={mfaOn ? "green" : "amber"}>
                  {mfaOn ? "Enrolled" : "Not enrolled"}
                </Badge>
                {!mfaOn ? (
                  <Button asChild size="1" variant="soft">
                    <Link href="/account/mfa-activate">
                      <LockClosedIcon /> Enable
                    </Link>
                  </Button>
                ) : (
                  <Button asChild size="1" variant="ghost">
                    <Link href="/account/recovery-codes">Recovery codes</Link>
                  </Button>
                )}
              </Flex>
            }
          />
          {user.is_staff ? <Row label="Role" value={<Badge color="blue">Staff</Badge>} /> : null}
        </Flex>
      </Flex>
    </Container>
  );
}

function Row({ label, value }: { label: string; value: React.ReactNode }) {
  return (
    <Flex
      justify="between"
      align="center"
      py="2"
      style={{ borderBottom: "1px solid var(--gray-a4)" }}
    >
      <Text size="2" color="gray">
        {label}
      </Text>
      <Text size="2">{value}</Text>
    </Flex>
  );
}

// crates/templates/files/{{cookiecutter.project_slug}}/{% if cookiecutter.frontend != 'nuxt' or cookiecutter.is_skeleton %}__SKIP__{% endif %}frontend/app/pages/account/profile.vue
<script setup lang="ts">
definePageMeta({ middleware: "auth" });

const auth = useAuthStore();
const { user } = storeToRefs(auth);
const mfaOn = computed(() => user.value?.has_usable_mfa === true);

useSeoMeta({ title: "Profile" });
</script>

<template>
  <section v-if="user" class="space-y-5 py-6">
    <header>
      <h1 class="text-3xl font-semibold">Your profile</h1>
      <p class="mt-1 text-sm text-slate-600 dark:text-slate-400">Signed in as {{ user.email }}</p>
    </header>
    <div class="divide-y divide-slate-200 rounded-md border border-slate-200 dark:divide-slate-800 dark:border-slate-800">
      <div class="flex items-center justify-between px-4 py-3">
        <span class="text-sm text-slate-600 dark:text-slate-400">Email</span>
        <span class="text-sm">{{ user.email }}</span>
      </div>
      <div class="flex items-center justify-between px-4 py-3">
        <span class="text-sm text-slate-600 dark:text-slate-400">Full name</span>
        <span class="text-sm">{{ user.full_name || "—" }}</span>
      </div>
      <div class="flex items-center justify-between px-4 py-3">
        <span class="text-sm text-slate-600 dark:text-slate-400">Multi-factor auth</span>
        <span class="flex items-center gap-3 text-sm">
          <span
            :class="[
              'rounded-full px-2 py-0.5 text-xs font-medium',
              mfaOn ? 'bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-100' : 'bg-amber-100 text-amber-800 dark:bg-amber-900 dark:text-amber-100',
            ]"
          >
            {{ mfaOn ? "Enrolled" : "Not enrolled" }}
          </span>
          <NuxtLink
            v-if="!mfaOn"
            to="/account/mfa-activate"
            class="rounded-md bg-slate-900 px-3 py-1 text-xs text-white hover:bg-slate-700 dark:bg-slate-100 dark:text-slate-900"
          >
            Enable
          </NuxtLink>
          <NuxtLink v-else to="/account/recovery-codes" class="underline">Recovery codes</NuxtLink>
        </span>
      </div>
      <div v-if="user.is_staff" class="flex items-center justify-between px-4 py-3">
        <span class="text-sm text-slate-600 dark:text-slate-400">Role</span>
        <span class="rounded-full bg-blue-100 px-2 py-0.5 text-xs font-medium text-blue-800 dark:bg-blue-900 dark:text-blue-100">Staff</span>
      </div>
    </div>
  </section>
</template>
